const content = $bit({
    tag: 'div',
    class: 'content',
    wrap: {
        tag: 'div',
        class: 'wrapper',
    },
    child: [{
            tag: 'h1',
            text: 'OnBit',
        },{
            tag: 'img',
            src: 'image/1.gif',
            id: 'main-gif',
            title: 'click mee!',
            style: 'cursor:pointer;'
        },{
            tag: 'div',
            id: 'description',
                child: {
                    tag: 'span',
                    html: `Bit is power!<br>You can create dynamic elements, pages, and more. <br> This page is generated by $bit`
                }
        }],
        parent: document.body
    });

content.querySelector('#main-gif').addEventListener('click', ()=> {
    alert('YOOHUUU!');
});

$bit({
    tag: 'div',
    id: 'links-area',
    child: [{
        tag: 'a',
        target: '_blank',
        text: 'GitHub',
        href: 'https://github.com/lihted/bit'
    }],
    parent: content
});

$bit({
    tag: 'div',
    child: {
        tag: 'span',
        text: new Date().getFullYear()
    },
    parent: content
})

